### ISSUE TITLE
Suggestion: App Search

### ISSUE THREAD

**Issue by techcoder20** [Pi-Apps-Coders/website#14]
I think it would be nice for new comers if they had a way to check if there is a specific app in pi-app. sure there are ways to check if an app is there by checking the wiki or the apps folder but for the absoulte begginer (who usually use pi-apps) they would probably find a search function in the pi-apps website useful to check if the app they want is there or not

**Comment by ryanfortner** [comment]
I created a github action for the apps list on the docs repo: https://docs.pi-apps.io/apps-list/, which does have search in the nav bar, but the only problem is that the images aren't loading. I don't think mkdocs supports html in markdown.

**Comment by techcoder20** [comment]
Mkdocs is not the problem. The links are wrong. I changed it in this pr https://github.com/Pi-Apps-Coders/docs/pull/1
