### ISSUE TITLE
Opening the Website Pins 1 or more CPU threads to 100% usage

### ISSUE THREAD

**Issue by theofficialgman** [Pi-Apps-Coders/website#19]
This appears to have always happened for me. it happens on my desktop (intel cpu) and switch (arm64 cpu).

No other websites I visit do this. is there some sort of infinite loop running here? The thread name is DedicatedWorker thats at 100% when using chromium

**Comment by theofficialgman** [comment]
I should also note I've tested on chromium and firefox based browsers and it happens on both

**Comment by theofficialgman** [comment]
it looks to me like this javascript code is running 100% of the time. `main-duco.js`

![image](https://user-images.githubusercontent.com/28281419/170551243-d456ea67-bf68-4e77-9c21-b75acde47740.png)

**Comment by Itai-Nelken** [comment]
I looked at that script and it looks as if it's mining for duino-coins (a cryptocurrency)!
That explains the high CPU usage.

**Comment by ryanfortner** [comment]
See the comment here: https://github.com/Botspot/pi-apps/pull/1887#issuecomment-1138907732

**Comment by theofficialgman** [comment]
@ryanfortner I am very close to submitting a github abuse report for you and this repository https://support.github.com/contact/report-abuse?category=report-abuse&report=other&report_type=unspecified#contact_comments

@Botspot has not given you permission to use the pi-apps name and mine crypto for your self for anyone that visits the website.

I have removed the reference link from the readme. if you do not remove this miner from the website ASAP, I will file the form and get this repo banned.

You do not pay hosting costs and do not own any of the pi-apps content yourself. if you want to make income off of it, I suggest you contact @Botspot publicly

edit:
I have seen your comment, that does not wipe your state clean. this isn't an experiment, its a deployed site. you could run an experiment on your own device and leave it running for 24hrs to see how much it makes.

its also terrible for battery life and user experience.

Deploying this without notification and without even a commit message stating what you have done is not cool

**Comment by ryanfortner** [comment]
I have removed the duinotize files (main-duco.js and duinotize.js). The website should use far less CPU. 

I apologize for not notifying anyone about this, however keep in mind, this is a site I maintain and I felt like for that reason it would be ok to add this in the background.

**Comment by theofficialgman** [comment]
> I apologize for not notifying anyone about this, however keep in mind, this is a site I maintain and I felt like for that reason it would be ok to add this in the background.

even without registered trademark, Botspot still own the trademark to pi-apps (in most countries this is the law). The side you maintain (not host, github does that) is under that trademark. I'd say it should at minimum be discussed with the trademark owner before you implement something of the sort. 
We don't want to have to get legal about this.
