### ISSUE TITLE
Adding cursor effects

### ISSUE THREAD

**Issue by ryanfortner** [Pi-Apps-Coders/website#20]
I found this cursor effects project and I was thinking about adding one of the effects to our website. 

GitHub repo: https://github.com/tholman/cursor-effects
Demo link: https://tholman.com/cursor-effects/

Opening an issue first just in case the community isn't in favor of this idea, because it's not for everyone.

**Comment by Itai-Nelken** [comment]
I like the effects, but I don't think they belong in the pi-apps website.

**Comment by ryanfortner** [comment]
Makes sense. I spoke to Botspot about this, he doesn’t want them in the site also. Closing now
