### ISSUE TITLE
Header not the same in index.html & screenshots.html

### ISSUE THREAD

**Issue by Jai-JAP** [Pi-Apps-Coders/website#4]
![image](https://user-images.githubusercontent.com/78354625/143527213-2817c85f-ef35-4941-bb9b-9d67eee2daf4.png)
index.html

![image](https://user-images.githubusercontent.com/78354625/143527322-b0fe6182-4ab4-4c67-9c18-b55532f7f82b.png)
screenshots.html

I have made a pull request that changes Pi-Apps text to its logo in Home button
But I dont know how to fix fonts

Also a suggestion
Make all screenshots centered in screenshots.html & maintain spacing in between images

**Comment by ryanfortner** [comment]
I centered the images and properly spaced them, but I'm still working on the fonts.

**Comment by ryanfortner** [comment]
Fixed the font issue. Closing now
