### ISSUE TITLE
Page content not fully visible in mobile devices

### ISSUE THREAD

**Issue by Jai-JAP** [Pi-Apps-Coders/website#8]
Home page mobile
![Home mobile](https://user-images.githubusercontent.com/78354625/144745035-e70e5a2f-5da9-42f0-acc8-7c11639ee35f.jpg)

Home page desktop
![Home desktop](https://user-images.githubusercontent.com/78354625/144745101-44ca172e-769f-4e78-931d-cbea1df92b09.jpg)

Screenshots page mobile
![Screenshots mobile](https://user-images.githubusercontent.com/78354625/144745149-6f81bb46-9dda-4105-ac07-745e88018b75.jpg)

Screenshots page desktop
![Screenshots desktop](https://user-images.githubusercontent.com/78354625/144745078-40bac96f-643d-46cf-8332-27aafb29ffb2.jpg)

**Comment by Jai-JAP** [comment]
All screenshots are taken on the topmost of the page On Mozilla Firefox browser on a phone (desktop ones with desktop mode enabled)

**Comment by ryanfortner** [comment]
Is the appearance any different while using another mobile browser, other than Firefox?

**Comment by Jai-JAP** [comment]
No.
Its almost the same in chrome.

**Comment by ryanfortner** [comment]
@techcoder20 has made some significant improvements to the site. Could you try the mobile view again please?

**Comment by Itai-Nelken** [comment]
Looks great on mobile (chrome). The screenshots are a bit streched, but it isn't very noticeable.

**Comment by Jai-JAP** [comment]
Looks great on mobile version of firefox too, except the screenshots.
Also the support.html should have some margins on the top in mobile view.

**Comment by ryanfortner** [comment]
I think I fixed the screenshots issue! removing the `custom-size` flag from each of the carousel images seemed to work.

**Comment by Jai-JAP** [comment]
Yes that's it screenshots are fixed
